version: '3.8'

services:
  # PostgreSQL Database
  postgres-db:
    image: postgres:13
    container_name: postgres-guarderia-danne-db
    environment:
      POSTGRES_DB: "guarderia-danne-db"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
