import short from "short-uuid"
import {UsersIcon} from "@sanity/icons"

export default {
  name: 'child',
  type: 'document',
  title: 'Niños',
  icon: UsersIcon,
  preview: {
    select: {
      title: 'full_name',
      subtitle: 'nickname'
    },
  },
  fields: [
    {
      name: 'full_name',
      title: 'Nombre Completo',
      type: 'string',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'parent_consultation_code',
      title: 'Codigo De Consulta Del Padre',
      type: 'string', 
      readOnly: true,
      initialValue: () => `F${short.generate()}`,
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'entry_time',
      title: 'Horario de Entrada',
      type: 'string', 
      options: {
        list: [
          {title: '7:00 AM', value: '7:00 AM'},
          {title: '7:30 AM', value: '7:30 AM'},
          {title: '8:00 AM', value: '8:00 AM'},
          {title: '8:30 AM', value: '8:30 AM'},
          {title: '9:00 AM', value: '9:00 AM'},
          {title: '9:30 AM', value: '9:30 AM'},
          {title: '10:00 AM', value: '10:00 AM'},
          {title: '10:30 AM', value: '10:30 AM'},
          {title: '11:00 AM', value: '11:00 AM'},
          {title: '11:30 AM', value: '11:30 AM'},
          {title: '12:00 PM', value: '12:00 PM'},
          {title: '12:30 PM', value: '12:30 PM'},
          {title: '1:00 PM', value: '1:00 PM'},
          {title: '1:30 PM', value: '1:30 PM'},
          {title: '2:00 PM', value: '2:00 PM'},
          {title: '2:30 PM', value: '2:30 PM'},
          {title: '3:00 PM', value: '3:00 PM'},
          {title: '3:30 PM', value: '3:30 PM'},
          {title: '4:00 PM', value: '4:00 PM'},
          {title: '4:30 PM', value: '4:30 PM'},
          {title: '5:00 PM', value: '5:00 PM'},
          {title: '5:30 PM', value: '5:30 PM'},
          {title: '6:00 PM', value: '6:00 PM'},
        ],
      },
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'exit_time',
      title: 'Horario de Salida',
      type: 'string', 
      options: {
        list: [
          {title: '7:00 AM', value: '7:00 AM'},
          {title: '7:30 AM', value: '7:30 AM'},
          {title: '8:00 AM', value: '8:00 AM'},
          {title: '8:30 AM', value: '8:30 AM'},
          {title: '9:00 AM', value: '9:00 AM'},
          {title: '9:30 AM', value: '9:30 AM'},
          {title: '10:00 AM', value: '10:00 AM'},
          {title: '10:30 AM', value: '10:30 AM'},
          {title: '11:00 AM', value: '11:00 AM'},
          {title: '11:30 AM', value: '11:30 AM'},
          {title: '12:00 PM', value: '12:00 PM'},
          {title: '12:30 PM', value: '12:30 PM'},
          {title: '1:00 PM', value: '1:00 PM'},
          {title: '1:30 PM', value: '1:30 PM'},
          {title: '2:00 PM', value: '2:00 PM'},
          {title: '2:30 PM', value: '2:30 PM'},
          {title: '3:00 PM', value: '3:00 PM'},
          {title: '3:30 PM', value: '3:30 PM'},
          {title: '4:00 PM', value: '4:00 PM'},
          {title: '4:30 PM', value: '4:30 PM'},
          {title: '5:00 PM', value: '5:00 PM'},
          {title: '5:30 PM', value: '5:30 PM'},
          {title: '6:00 PM', value: '6:00 PM'},
        ],
      },
      validation: (Rule) => Rule.required(),
    },

    {
      name: 'nickname',
      title: 'Apodo',
      type: 'string',
    },
    {
      name: 'date_of_birth',
      title: 'Fecha de Nacimiento',
      type: 'date', 
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'nationality',
      title: 'Nacionalidad',
      type: 'string',
    },
    {
      name: 'age',
      title: 'Edad',
      type: 'number',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'blood_type',
      title: 'Tipo de Sangre',
      type: 'string',
      options: {
        list: [
          {title: 'A+', value: 'A+'},
          {title: 'A-', value: 'A-'},
          {title: 'B+', value: 'B+'},
          {title: 'B-', value: 'B-'},
          {title: 'AB+', value: 'AB+'},
          {title: 'AB-', value: 'AB-'},
          {title: 'O+', value: 'O+'},
          {title: 'O-', value: 'O-'},
          {title: 'Desconocido', value: 'Desconocido'},
        ],
      },
    },
    {
      name: 'residence_phone',
      title: 'Teléfono de Residencia',
      type: 'string',
    },
    {
      name: 'guardian',
      title: 'Tutor',
      type: 'string',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'lives_with_parents',
      title: 'Vive con Padres',
      type: 'string',
      options: {
        list: ['SI', 'NO'],
      },
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'contact_number',
      title: 'Número de Contacto',
      type: 'string',
    },
    {
      name: 'emergency_contact_person',
      title: 'Persona de Emergencia',
      type: 'string',
    },
    {
      name: 'relationship',
      title: 'Parentesco',
      type: 'array',
      validation: (Rule) => Rule.required(),
      of: [{type: 'string'}],
      options: {
        list: [
          'Mama',
          'Papa',
          'Ninguno'
        ],
      },
    },
    {
      name: 'has_disease',
      title: 'Padece Enfermedad',
      type: 'string',
      validation: (Rule) => Rule.required(),
      options: {
        list: ['SI', 'NO'],
      },
    },
    {
      name: 'disease_history',
      title: 'Enfermedad Padecida',
      type: 'text',
    },
    {
      name: 'required_medications',
      title: 'Medicamentos Requeridos',
      type: 'text',
    },
    {
      name: 'is_allergic',
      title: 'Es Alérgico',
      type: 'string',
      validation: (Rule) => Rule.required(),
      options: {
        list: ['SI', 'NO'],
      },
    },
    {
      name: 'vaccinations_up_to_date',
      title: 'Vacunas al Día',
      type: 'string',
      validation: (Rule) => Rule.required(),
      options: {
        list: ['SI', 'NO'],
      },
    },
    {
      name: 'has_medical_insurance',
      title: 'Tiene Seguro Médico',
      type: 'string',
      validation: (Rule) => Rule.required(),
      options: {
        list: ['SI', 'NO'],
      },
    },
    {
      name: 'suffers_from',
      title: 'Padece',
      type: 'array',
      validation: (Rule) => Rule.required(),
      of: [{type: 'string'}],
      options: {
        list: [
          'Sarampión',
          'Dolor de Cabeza',
          'Varicela',
          'Dolor de Oídos',
          'Paperas',
          'Diabetes',
          'Meningitis',
          'Dolor de Garganta',
          'Hepatitis',
          'Crisis Asmática',
          'Sin Especificar'
        ],
      },
    },
    {
      name: 'pediatrician',
      title: 'Pediatra',
      type: 'string',
    },
    {
      name: 'pediatrician_contact',
      title: 'Contacto del Pediatra',
      type: 'string',
    },
    {
      name: 'frequently_feels',
      title: 'Frecuentemente se Siente',
      type: 'array',
      validation: (Rule) => Rule.required(),
      of: [{type: 'string'}],
      options: {
        list: [
          'Triste',
          'Llora con Frecuencia',
          'Dinámico',
          'Se Enoja Frecuentemente',
          'Tímido',
          'Se Encierra en Sí',
          'Cuando se Enoja es Agresivo',
          'Trata de Llamar la Atención',
          'Es Posesivo',
          'Es Independiente',
          'Es Desobediente',
          'Es Desordenado',
          'Es Ordenado',
          'Sin Especificar'
        ],
      },
    },
    {
      name: 'father_name',
      title: 'Nombre del Padre',
      type: 'string',
    },
    {
      name: 'father_work_phone',
      title: 'Teléfono del Trabajo del Padre',
      type: 'string',
    },
    {
      name: 'father_cell_phone',
      title: 'Teléfono Celular del Padre',
      type: 'string',
    },
    {
      name: 'father_email',
      title: 'Correo Electrónico del Padre',
      type: 'string',
    },
    {
      name: 'father_address',
      title: 'Dirección del Padre',
      type: 'string',
    },
    {
      name: 'father_sector',
      title: 'Sector del Padre',
      type: 'string',
    },
    {
      name: 'mother_name',
      title: 'Nombre de la Madre',
      type: 'string',
    },
    {
      name: 'mother_work_phone',
      title: 'Teléfono del Trabajo de la Madre',
      type: 'string',
    },
    {
      name: 'mother_cell_phone',
      title: 'Teléfono Celular de la Madre',
      type: 'string',
    },
    {
      name: 'mother_email',
      title: 'Correo Electrónico de la Madre',
      type: 'string',
    },  {
      name: 'mother_address',
      title: 'Dirección del Madre',
      type: 'string',
    },
    {
      name: 'mother_sector',
      title: 'Sector del Madre',
      type: 'string',
    },
  ],
}
