name: Sanity Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Sanity CLI
        run: npm install -g @sanity/cli
        working-directory: ./backend

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Build Sanity Studio
        run: npm run build
        working-directory: ./backend

      - name: Deploy Sanity Studio
        run:  SANITY_AUTH_TOKEN=${{ secrets.SANITY_AUTH_TOKEN }} npx sanity deploy --dataset production --yes
        working-directory: ./backend
