name: Sanity Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Change directory to backend
        run: cd backend

      - name: Install Sanity CLI
        run: npm install -g @sanity/cli

      - name: Install dependencies
        run: npm install

      - name: Build Sanity Studio
        run: npm run build

      - name: Deploy Sanity Studio
        run: npx sanity deploy --token ${{ secrets.SANITY_TOKEN }} --dataset ${{ secrets.SANITY_ENVIRONMENT }} --yes
